site_name: Blue Manual 
markdown_extensions:
    - def_list
    - tables 
    - toc:
        separator: '_'
theme:
    name: material
    features: 
      - tabs
nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Preface': 'preface.md'
        - 'Getting Started': 
            - 'Introduction': 'users/gettingStarted/usersIntro.md'
            - 'Installation': 'users/gettingStarted/installation.md'
            - 'Program Options': 'users/gettingStarted/programOptions.md'
            - 'Primary Editors':
              - 'Score Timeline': 'users/gettingStarted/primaryEditors/scoreTimeline.md'
              - 'Orchestra Manager': 'users/gettingStarted/primaryEditors/orchestraManager.md'
              - 'UDO Manager': 'users/gettingStarted/primaryEditors/udoManager.md'
              - 'Project Properties': 'users/gettingStarted/primaryEditors/projectProperties.md'
              - 'Mixer': 'users/gettingStarted/primaryEditors/mixer.md'
              - 'Blue Live': 'users/gettingStarted/primaryEditors/blueLive.md'
              - 'Tables Manager': 'users/gettingStarted/primaryEditors/tablesManager.md'
              - 'Globals Manager': 'users/gettingStarted/primaryEditors/globalsManager.md'
            - 'Tools':
              - 'Code Editor': 'users/gettingStarted/tools/codeEditor.md'
              - 'Blue Share': 'users/gettingStarted/tools/blueShare.md'
              - 'Code Repository': 'users/gettingStarted/tools/codeRepository.md'
              - 'Effects Library': 'users/gettingStarted/tools/effectsLibrary.md'
              - '.csoundrc Editor': 'users/gettingStarted/tools/csoundrcEditor.md'
              - 'Scanned Matrix': 'users/gettingStarted/tools/scannedMatrix.md'
              - 'SoundFont Viewer': 'users/gettingStarted/tools/soundFontViewer.md'
              - 'FTable Converter': 'users/gettingStarted/tools/ftableConverter.md'
              - 'Python Console': 'users/gettingStarted/tools/pythonConsole.md'
            - 'Other Features': 
               - 'Auto Backup': 'users/gettingStarted/otherFeatures/autoBackup.md'
               - 'SoundObject Freezing': 'users/gettingStarted/otherFeatures/soundObjectFreezing.md'
               - 'Audition SoundObjects': 'users/gettingStarted/otherFeatures/auditionSoundObjects.md'
               - 'Import CSD': 'users/gettingStarted/otherFeatures/importCSD.md'
               - 'Import MIDI': 'users/gettingStarted/otherFeatures/importMIDI.md'
               - 'Blue Variables': 'users/gettingStarted/otherFeatures/blueVariables.md'
               - 'Commandline': 'users/gettingStarted/otherFeatures/commandLine.md'
        - 'Concepts':
            - 'Rendering': 'users/concepts/rendering.md'
            - 'Sound Objects': 'users/concepts/soundObjects.md'
            - 'PolyObjects': 'users/concepts/polyObjects.md'
            - 'Note Processors': 'users/concepts/noteProcessors.md'
            - 'SoundObject Library': 'users/concepts/soundObjectLibrary.md'
            - 'Parameter Automation': 'users/concepts/parameterAutomation.md'
            - 'Command Blocks': 'users/concepts/commandBlocks.md'
    - 'Tutorials':
        - 'First Project': 'tutorials/tutorial_first_project.md' 
        - 'Scripting': 'tutorials/tutorial_scripting.md' 
        - 'Sound SoundObject': 'tutorials/tutorial_sound_soundObject.md' 
    - 'Reference':
        - 'SoundObjects': 
          - 'Introduction': 'users/reference/soundObjects/top.md'
          - 'AudioFile': 'users/reference/soundObjects/audioFileObject.md'
          #- 'CeciliaModule': 'users/reference/soundObjects/ceciliaModule.md'
          - 'Comment': 'users/reference/soundObjects/comment.md'
          - 'Clojure': 'users/reference/soundObjects/clojureObject.md'
          - 'External': 'users/reference/soundObjects/external.md'
          - 'GenericScore': 'users/reference/soundObjects/genericScore.md'
          - 'Instance': 'users/reference/soundObjects/instance.md'
          - 'Javascript': 'users/reference/soundObjects/javaScriptObject.md'
          - 'JMask': 'users/reference/soundObjects/jmask.md'
          - 'LineObject': 'users/reference/soundObjects/lineObject.md'
          - 'ObjectBuilder': 'users/reference/soundObjects/objectBuilder.md'
          - 'Pattern': 'users/reference/soundObjects/patternObject.md'
          - 'PianoRoll': 'users/reference/soundObjects/pianoRoll.md'
          - 'PolyObject': 'users/reference/soundObjects/polyObject.md'
          - 'Python': 'users/reference/soundObjects/pythonObject.md'
          - 'Sound': 'users/reference/soundObjects/sound.md'
          - 'Tracker': 'users/reference/soundObjects/tracker.md'
          - 'ZakLineObject': 'users/reference/soundObjects/zakLineObject.md'
        - 'Note Processors': 
          - 'Introduction': 'users/reference/noteProcessors/top.md' 
          - 'AddProcessor': 'users/reference/noteProcessors/addProcessor.md' 
          - 'EqualsProcessor': 'users/reference/noteProcessors/equalsProcessor.md' 
          - 'InversionProcessor': 'users/reference/noteProcessors/inversionProcessor.md' 
          - 'LineAdd': 'users/reference/noteProcessors/lineAddProcessor.md' 
          - 'LineMultiply': 'users/reference/noteProcessors/lineMultiplyProcessor.md' 
          - 'Multiply': 'users/reference/noteProcessors/multiplyProcessor.md' 
          - 'PchAdd': 'users/reference/noteProcessors/pchAddProcessor.md' 
          - 'PchInversion': 'users/reference/noteProcessors/pchInversionProcessor.md' 
          - 'Python': 'users/reference/noteProcessors/pythonProcessor.md' 
          - 'RandomAdd': 'users/reference/noteProcessors/randomAddProcessor.md' 
          - 'RandomMultiply': 'users/reference/noteProcessors/randomMultiplyProcessor.md' 
          - 'Retrograde': 'users/reference/noteProcessors/retrogradeProcessor.md' 
          - 'Rotate': 'users/reference/noteProcessors/rotateProcessor.md' 
          - 'SubList': 'users/reference/noteProcessors/subListProcessor.md' 
          - 'Switch': 'users/reference/noteProcessors/switchProcessor.md' 
          - 'TimeWarp': 'users/reference/noteProcessors/timeWarpProcessor.md' 
          - 'Tuning': 'users/reference/noteProcessors/tuningProcessor.md' 
        - 'Instruments': 
          - 'Introduction': 'users/reference/instruments/top.md' 
          - 'GenericInstrument': 'users/reference/instruments/genericInstrument.md' 
          - 'Python': 'users/reference/instruments/pythonInstrument.md' 
          - 'Javascript': 'users/reference/instruments/javaScriptInstrument.md' 
          - 'BlueX7': 'users/reference/instruments/blueX7.md' 
          - 'BlueSynthBuilder': 'users/reference/instruments/blueSynthBuilder.md' 
        - 'Shortcuts': 'users/reference/shortcuts.md'
