# Globals Manager

Csound Orchestra and Score text can be passed directly into a generated
CSD by using the Global Orchestra and Global Score windows.

## Global Orchestra

Anything here will be inserted into the <CsOrchestra\> section of the
.CSD file before anything generated by the Orchestra. Things like global
variables, macros, or GUI instrument definitions may go here.

## Global Score 

Anything here will be inserted into <CsScore\> section of the .CSD file
before anything generated by the score timeline. the global score's
processing is done outside of the score timelines, so any notes put here
are not factored into values calculated from the timeline, like total
duration, nor are any notes in the global score section translated like
the timeline is when a different start time is used other than 0.0. for
instance, if you use 2.0 as a start time, a note in the score timeline
at 2.0 will be translated to start at 0.0, while a note with a start
time of 2.0 in the global score section is not affected and will start
at time 2.0.

There are also certain variables made available from Blue (Blue
variables) that are useful for specific purposes. One of them is
<TOTAL\_DUR\>. An example of its use is:

    i20 0 [<TOTAL_DUR> + 10] .95 1 1000

The note given above is for a global effect(a global reverb unit). This
note will always start at time zero regardless of when the score starts,
and will always last as long as the duration of the generated score from
the timeline plus 10 seconds. Because Blue variables are a text swap,
the above use of the bracket notation that Csound uses was necessary.
For a score with a 20 second duration, the above note would have been
generated as:

    i20 0 [20 + 10] .95 1 1000

Because of the Blue variable used, the note will correclty play
regardless of when the score starts. If the the Blue variable was note
used and was put as a note in the Score timeline, the reverb may not
run.

!!! note
    When Blue variables were created, Blue did not have a Mixer system
    implemented. The above system continues to function, the practice of
    using the Mixer is highly recommended. This feature is left in for
    legacy projects.
